version: '3.8'
services:
  gcpn:
    image: rl-training
    build:
        context: .
        shm_size: '10gb'
    shm_size: '10gb'  
    volumes:
      - .:/app
    environment:
      LOG_LEVEL: "DEBUG"
    ports:
      - 6006:6006